services:
    - type: web
      name: strapi
      env: node
      plan: free
      rootDir: backend
      buildCommand: npm install && npm run build
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: DATABASE_URL
            fromDatabase:
                name: strapi-db
                property: connectionString
          - key: JWT_SECRET
            generateValue: true
          - key: ADMIN_JWT_SECRET
            generateValue: true
          - key: APP_KEYS
            generateValue: true
          - key: API_TOKEN_SALT
            generateValue: true

databases:
    - name: strapi-db
      plan: free
